### PR TITLE
Refactor into separate modules (and lint)

### LINKED ISSUE #173: Refactor main module into multiple modules
My linters really struggle with this ~10K `__init__.py`.  Could refactor into:
 - models module
 - views module
 - controllers module
 - exceptions module
 - helper/util funcs module

Would need to think about where globals are defined and how they are accessed/mutated.  A good opportunity to convert globals into attributes of a singleton object?

### PR DESCRIPTION
**Pull request by willfurnass**
I've refactored `__init__.py` into several modules.  Now `__init__.py` only effectively exports the functions and classes we want to present as the public API; it contains very little code.  The list of modules in the package is now as follows:

```sh
$ ls -1 mumot/*py
mumot/consts.py
mumot/controllers.py
mumot/defaults.py
mumot/exceptions.py
mumot/__init__.py
mumot/models.py
mumot/utils.py
mumot/_version.py
mumot/views.py
```

This PR also includes many changes relating to linting/basic refactoring plus some additional type hints. 

Closes #173

(Sorry, this is a PR From Hell)

### CODE REVIEW

**Comment by jarmarshall** [comment]
@joefresna ’s comments seems sensible to me...

**Comment by willfurnass** [comment]
- [X] Move _round_to_1 and _make_autopct funcs from view.py to utils.py
- [X] Move LINE_COLOR_LIST and MULTIPLOT_COLUMNS constants from views module to consts module
- [X] Move NetworkType class from models.py to consts.py
- [X] Move _decodeNetworkTypeFromString and _encodeNetworkTypeToString from models.py to utils.py
- [X] Move _raiseModelError func from models.py to exceptions.py
- [ ] Move _deriveODEsFromRules, _deriveMasterEquation, and _doVanKampenExpansion funcs from models.py to views.py

**Comment by willfurnass** [comment]
@joefresna Happy with the interactive behavior (widgets and plots) for the HEAD of this branch?

**Comment by willfurnass** [comment]
And thanks for the review!

**Comment by joefresna** [comment]
> @joefresna Happy with the interactive behavior (widgets and plots) for the HEAD of this branch?

How can I checkout this branch?
```
git checkout split_module
error: pathspec 'split_module' did not match any file(s) known to git
```

**Comment by willfurnass** [comment]
```shgit remote add willfurnass git@github.com:willfurnass/MuMoT.git
git remote -v
git fetch --prune --all
git branch -vva
git checkout split_module

**Comment by joefresna** [comment]
```
JF-MacBook:MuMoT joefresna$ git remote -v
origin	https://github.com/DiODeProject/MuMoT.git (fetch)
origin	https://github.com/DiODeProject/MuMoT.git (push)
willfurnass	git@github.com:willfurnass/MuMoT.git (fetch)
willfurnass	git@github.com:willfurnass/MuMoT.git (push)
JF-MacBook:MuMoT joefresna$ git fetch --prune --all
Fetching origin
Fetching willfurnass
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch willfurnass
```

**Comment by willfurnass** [comment]
@joefresna If you haven't [set up SSH access to GitHub](https://help.github.com/en/articles/which-remote-url-should-i-use) then you'll need to now run the following to change the URL for the `willfurnass` [remote](https://help.github.com/en/articles/adding-a-remote) so it uses HTTPS instead of SSH:

```sh
git remote set-url willfurnass https://github.com/willfurnass/MuMoT.git
git remote -v
git fetch --prune --all
git branch -vva
git checkout split_module
```

**Comment by joefresna** [comment]
Thanks, @willfurnass , I now solved and I can run this branch.

> @joefresna Happy with the interactive behavior (widgets and plots) for the HEAD of this branch?

I checked the widgets and plots and the results look correct, and interactivity is working fine.

I guess the refactoring changes are now completed, and from my side I'm happy to proceed with the Merging. Thanks.

**Pull request merged**
