### PR TITLE
Do not calculate code coverage for 3rd party code

### PR DESCRIPTION
**Pull request by willfurnass**
See #247

### CODE REVIEW

**Comment by jarmarshall** [comment]
CI test has failed but I don’t think it’s to do with the changes

**Comment by willfurnass** [comment]
Rebased on `upstream/master`; let's see if that helps.

**Comment by willfurnass** [comment]
The CI job ran successfully this time but the codecov report shows that coverage info from e.g. `gen/*py` is still included in its stats...

Ideas for how to use codecov + pytest-cov together that might help here: https://github.com/pytest-dev/pytest-cov/issues/130

**Comment by jarmarshall** [comment]
@willfurnass I prefer not to include tests for other packages as they could get out of date; simpler to exclude folders, but I could not quite follow the advice from the GitHub issue you linked to, not having set up the CodeCov configuration...

**Comment by willfurnass** [comment]
I've revised the the `omit` paths in `.coveragerc` to see if I can get codecov to ignore the `process_latex` and `gen` dirs.  NB I still think that either these dirs should be accounted for in the coverage stats _or_ tests for those modules are imported into / implemented in this package.

**Comment by willfurnass** [comment]
Superseded by #298

**Pull request closed without merging**
