### PR TITLE
Test deploying to gh-pages

### PR DESCRIPTION
**Pull request by willfurnass**

### CODE REVIEW

**Comment by jarmarshall** [comment]
@willfurnass is this ready to go? Thanks

**Comment by willfurnass** [comment]
@jarmarshall Sorry, been busy with other things.

**Comment by willfurnass** [comment]
Testing that Travis deploys docs to `gh-pages` after merging this PR into `master`.  If that works as we'd like we need to update various things in the repo to point at / mention GitHub Pages instead of ReadTheDocs.

**Comment by jarmarshall** [comment]
Thanks - also in code comments where there are various references to readthedocs

**Pull request merged**
