### PR TITLE
Unpin sympy version (WIP)

### PR DESCRIPTION
**Pull request by willfurnass**
Attempts to address #170

### CODE REVIEW

**Comment by jarmarshall** [comment]
Is it possible to move this branch back to the DiODe project original @willfurnass ? Then it will be much easier to switch to that branch and checkout. For example, I had to clone your repo, switch to your PR branch, and then still when running the notebook and importing mumot I am getting the following error... (i.e. it is apparently referencing my original Git repo rather than yours)

```
Traceback (most recent call last):

  File "/anaconda3/envs/mumot-env/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-7b85ca79491d>", line 1, in <module>
    import mumot

  File "/Users/james/Google Drive/Home/Git/MuMoT/mumot/__init__.py", line 30, in <module>
    from .models import (

  File "/Users/james/Google Drive/Home/Git/MuMoT/mumot/models.py", line 114
    raise exceptions.MuMoTSyntaxError(f"Using substitute to rename reactants not supported: {sub[0]} = {sub[1]}")
                                                                                                               ^
SyntaxError: invalid syntax
```

When I fix that error in my clone of your repo obviously it doesn't help. Not sure where the error has been introduced mind...

**Comment by jarmarshall** [comment]
Update - this error also seems to be in the master branch as of at least commit https://github.com/DiODeProject/MuMoT/commit/0473be9bd195b01d565aea1fd4d16bc0290e33f4

**Comment by jarmarshall** [comment]
Looking in the history, @willfurnass , were several of these `f"` errors introduced by some kind of editor or search and replace problem?

**Comment by willfurnass** [comment]
@jarmarshall I created this feature branch in a fork to avoid cluttering the main repo with ephemeral branches.  However, this might be a bigger job than initially thought so I'll push this branch from my fork to the main repo to ensure we all have write access, then will create a new PR from that.

[f-strings](https://realpython.com/python-f-strings/) are supported in Python >= 3.6 - are you using an older Python locally?

**Comment by jarmarshall** [comment]
Sorry @willfurnass - I didn't realise the Python requirement had been updated and was unfamiliar with f-strings. I think we may need to sit down together however as this is causing me real problems now... I've done the following:
* updated to Python 3.7 (as per https://mumot.readthedocs.io/en/latest/install.html)
* introduced new ipython kernel (as per https://ipython.readthedocs.io/en/latest/install/kernel_install.html since Jupiter was still running on Python 3.5)

Now have activated my `mumot-env` from the command line, run Jupyter, activated by new ipython kernel, and matplotlib cannot be found.

**Pull request closed without merging**
