### PR TITLE
Updated demo notebook, about, and getting started

### PR DESCRIPTION
**Pull request by jarmarshall**

### CODE REVIEW

**Comment by willfurnass** [comment]
Does this need to go into 1.1.X i.e. do we need a 1.1.2 release?

**Comment by jarmarshall** [comment]
No, it's updating the docs to reflect the existence of the 1.1.1 release

**Comment by jarmarshall** [comment]
...all the files changed are outside of the PyPI release...

**Comment by jarmarshall** [comment]
OK, now I see the issue - because Sphinx displays the docs tagged in the 1.1.1 release rather than `HEAD` it's not possible to update those docs - it seems overkill however to push a 1.1.2 release when the code has not changed - how to do this, @willfurnass ? There are pending changes to the docs that need to be displayed for users...

**Comment by willfurnass** [comment]
FYI v1.1.2 now available via PyPI and associated DOI published.

**Pull request merged**
