### PR TITLE
Solve issue #202

### PR DESCRIPTION
**Pull request by tbose1**
I made changes in the  `_roundNumLogsOut()` which solve issue #202.

### CODE REVIEW

**Comment by willfurnass** [comment]
@tbose1 Please let the Travis CI tests run before merging a Pull Request into `master`.

**Comment by tbose1** [comment]
I thought Travis CI tests run automatically when creating a Pull Request and when I created the Pull Request some tests did seem to run, and there were no conflicts when they finished. Also, I made the code change in a feature branch (issue-#202) and made the Pull Request from this branch. @willfurnass have I missed something?

**Comment by willfurnass** [comment]
Okay, I'm not sure what's happened then:)  If you look back through this PR you'll see `0 of 2 checks passed` after clicking on *View details* next to commit `6df9a15` - this normally indicates that a PR was merged before the Travis CI jobs finished but that might not have been true in this case.

**Comment by tbose1** [comment]
I hope I remember correctly but I think GitHub indicated those tests passed successfully. However, next time I'll wait a bit longer before merging, just to be sure that testing has finished. Thanks for pointing out.

**Pull request merged**
