### PR TITLE
Implemented the download button

### LINKED ISSUE #9: Improve format of the exported data files
There is the possibility to download the simulation data file (e.g. through MuMoTmultiagentController.downloadTimeEvolution()), however the current data format is very basic and not properly formatted and should be improved.

### PR DESCRIPTION
**Pull request by joefresna**
This closes #9 #288

@jarmarshall , please check if ok

### CODE REVIEW

**Comment by jarmarshall** [comment]
Thanks - this seems to work well, but I see two issues:

1. files should be csv - that's a standard for importing these kind of data into other packages. Tab separating will often require the user to do some text processing, I expect.
2. the link should be a button with an appropriate icon; see how the bookmark button is implemented. An appropriate icon may be `fa-file-download` (see https://fontawesome.com/icons?d=gallery&q=download)

**Comment by jarmarshall** [comment]
3. in line with the separation of view / controller philosophy, a direct functional way of downloading data from a view should be provided.

**Comment by joefresna** [comment]
Great! Do you think that they can be Second Release enhancements?

**Comment by jarmarshall** [comment]
Sorry - need to get the basics right. These should be trivial changes to make though...

**Comment by joefresna** [comment]
I can take care of point 1 and 3.
I tried the number 2, there is commented code to create the button, but I could not make it work properly. I think this requires to define a new custom ipywidget for this... I might not be able to implement this.

**Comment by jarmarshall** [comment]
I can do 2) and 3) if you can do 1) @joefresna

**Comment by jarmarshall** [comment]
OK, messages crossed - I will look only at 2) then...

**Comment by jarmarshall** [comment]
Will wait for your commit, then pull and finalise 2)...

**Comment by joefresna** [comment]
which is the desired syntax of the file? comma between filed and `;` between lines?

**Comment by joefresna** [comment]
how would you prefer the view function?
`_downloadSimulationData()`

or

`downloadSimulationData()`

**Comment by joefresna** [comment]
Implemented 1 and 3. Should work.

**Comment by jarmarshall** [comment]
1) I think newline `\n`is correct; see for example https://nicercode.github.io/blog/2013-04-30-excel-and-line-endings/
3) I think a parameter-free `downloadTimeEvolution()` function in `MuMoTstochasticSimulationView` will be sufficient; I prefer that name as in the future I would like to add this functionality to `MuMoTtimeEvolutionView`-derived views

**Comment by joefresna** [comment]
point 1 uses \n.
please, feel free to rename into `downloadTimeEvolution` when implementing point (2).

**Comment by jarmarshall** [comment]
It turns out 2) is more complicated than I assumed - the existing solution is an HTML link, but a Button widget has an event handler - not clear a Button can be defined as a hyperlink, and not sure how to work this as a function call. I would like to make it work if at all possible though.

**Comment by joefresna** [comment]
yes, as commented before, the solution is to create a custom ipywidget.
Or at least, it is is what the ipywidget developer suggests: https://github.com/jupyter-widgets/ipywidgets/issues/1966

**Comment by jarmarshall** [comment]
I agree that a custom widget may be required to do this properly. For now that is too technical to get into; as an interim I have added the button to download results, and if clicked in an appropriate controller (derived from `MuMoTstochasticSimulationController`) the HTML download link will appear. If the button is clicked in an unsupported controller type, it displays an error message. Results download such as `MuMoTtimeEvolutionController` can be added for other views in subsequent releases.

**Comment by jarmarshall** [comment]
PS `downloadSimulationData()` has been renamed as `downloadResults()`

**Comment by jarmarshall** [comment]
@joefresna take a look and see what you think - the logic is that most users won't want to download results, so having a sleeker interface but slightly clunk route to the data for expert users is preferred over an interface that will change. Subsequently when we define a custom widget (issue #308) the process will be streamlined, but the interface most users see will not be changed.

Please merge if you're happy, although preferably after noon GMT as I'm giving a talk and may show the MyBinder deployment...

**Pull request merged**
