### PR TITLE
Refine info on creating releases

### PR DESCRIPTION
**Pull request by willfurnass**

### CODE REVIEW

**Comment by jarmarshall** [comment]
@willfurnass I followed the revised instructions through to step 9. Then I created a new environment, activated it, ran the command, and had the following error:
```Looking in indexes: https://test.pypi.org/simple/
Requirement already satisfied: mumot in /Users/james/Google Drive/Home/Git/MuMoT (1.0.0)
Collecting antlr4-python3-runtime==4.5.3 (from mumot)
  Could not find a version that satisfies the requirement antlr4-python3-runtime==4.5.3 (from mumot) (from versions: )
No matching distribution found for antlr4-python3-runtime==4.5.3 (from mumot)
```

**Comment by jarmarshall** [comment]
PS I have created a branch `1.0.0-release` but it is not yet visible at the master repository level - is there a `git commit` step missing from the instructions?

**Comment by willfurnass** [comment]
@jarmarshall Can you capture more output from the cmd that produced the 'No matching distribution found' error?  Was this Python pkg build command definitely using Python 3.6?

**Comment by jarmarshall** [comment]
This is everything @willfurnass ... I'm wondering if the TestPyPI package list doesn't include old versions, and this will be OK on PyPI - have been trying to see if I can find some info online about my hypothesis.

```
(mumot-env-release) James-iMac:MuMoT james$ python3 -m pip install --index-url https://test.pypi.org/simple/ mumot
Looking in indexes: https://test.pypi.org/simple/
Requirement already satisfied: mumot in /Users/james/Google Drive/Home/Git/MuMoT (1.0.0)
Collecting antlr4-python3-runtime==4.5.3 (from mumot)
  Could not find a version that satisfies the requirement antlr4-python3-runtime==4.5.3 (from mumot) (from versions: )
No matching distribution found for antlr4-python3-runtime==4.5.3 (from mumot)
```

**Comment by willfurnass** [comment]
I don't think antlr4-python3-runtime is on testpypi; c.f.:

```
$ pip install antlr4-python3-runtime==
Collecting antlr4-python3-runtime==
  Could not find a version that satisfies the requirement antlr4-python3-runtime== (from versions: 4.4.0, 4.4.1, 4.5, 4.5.2, 4.5.2.1, 4.5.3, 4.6, 4.7, 4.7.1, 4.7.2)
No matching distribution found for antlr4-python3-runtime==
```

and

```
$ pip install --index-url https://test.pypi.org/simple/ antlr4-python3-runtime==
Looking in indexes: https://test.pypi.org/simple/
Collecting antlr4-python3-runtime==
  Could not find a version that satisfies the requirement antlr4-python3-runtime== (from versions: )
No matching distribution found for antlr4-python3-runtime==
```

I suspect [--extra-index-url](https://packaging.python.org/guides/using-testpypi/#using-testpypi-with-pip) is what's needed here (not tested that yet).

**Comment by jarmarshall** [comment]
If this is the issue should I just try deploying to PyPI directly?

**Comment by jarmarshall** [comment]
Update: first I may try this https://stackoverflow.com/questions/34514703/pip-install-from-pypi-works-but-from-testpypi-fails-cannot-find-requirements

**Comment by jarmarshall** [comment]
So, from TestPyPI this is now partially working - going to open a new issue on refining the installation options

**Pull request merged**
